[package]
name = "idlemail"
version = "0.1.0"
authors = ["Markus Ebner <info@ebner-markus.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
pretty_env_logger = "^0.4"
anyhow = "^1.0"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
signal = "^0.7"
time = "^0.2"
lettre = { git = "https://github.com/lettre/lettre", rev = "123794a00dc8a2a03cfd7c7af273d5ffc178dc55" }
async-imap = "^0.2"
async-std = "^1.6"
futures = "^0.3"
async-native-tls = "^0.3"
native-tls = "^0.2"